language: python
python: 2.7
env:
  global:
    - secure: Lmstns3iW43NaxifZWXasCo0/Rxq8YKTEvgaIWxFVa6HFw8HUGpubrbk7snlF4NLcJIMlpIAKDAAO2fjKldqLEjp5hYPw8sfXqWpa7c3dO0CuSJg9Fb0w5hUulyyfqbLGe5uDxl+WoptPYfDp1fH1ZgBhS9m2bZc1fDeoREDIcBxn+DCoHuxsOSH6HsLI4AMWfNQ1q8LMscpbsGoN81RrMuYan5u6QvSeG0kVOZnf05bN5nvTovaLCUYdMf15qfwrMfCDAQqW4tKqLtWLlmDY0/0BC2MplzbwU1+UkQ1syI4sOw2PGIzL6nRLhdkk+6RZbs0KE2PRKkSWofkRU6zktl534VUixki4RyJnafLLs6rAl/36AMVuJ+qh89ptA1xXFfOE7A0molEAp3kpReW4jZQsfSFHudlyZhZCx5sDXHAXp6xK3eoBgOeXp1anTfqZcNHTgEI959HWgvlIA4w/p2vQ9InR+KTQBX8UnoTtGXwlNZG3gvHKU/WppC5COd/k3Am/JL28wq570damY2OtEg6zXbOkZfRmiKbCgGXOUogH6VmYQkRh1fNICwJQ8+w7nhcYLNDebu+QpLCLsKsjzW9KNu6xJjaD9l1D8xvVT0Rpl8ApdmWrZwBH3gXMy/x0EVYvY2lplfB+E9etBLR4NpPZGtFq8gEkiAmwG794p8=
notifications:
  slack:
    secure: BWgyVrdANtyj5Sp9PsMmmSS/dzDXy64pT6icsILhkmX8nUXH36vwNwunvBtuRdRJvMO9Ajo9dEuJoUk6li8NaZ2oM/JiaXdOepcmXosOyPGjoJ7hkMjoxHPAUmDqtVj4yzi6Wpk2dEKXmjjlT1u672iZ8L2D8SRa2PUIPOypl7IsAeDjtLkW2Dp8a1fg6K/A9rseIiSGoKNryCn8YfKBIZ/Dso99f9nOEPTE2gMt8CDC1rllneM17YuubIC/j5DRH+6Gxhd3vXzvUyu0mde9T4qh7xX4j6mGI7GSVPTd0O3p0wsLgOn8/1ku9Mhvkoae6gvRjKujfx6qwiSo7Vz5+r1n4+KwQT90Wfbkhr0md+taEIXbrbBjO+IkFYbc0sf6PhL2S4S5dM5bKHTcdqYXXZiEhcxCa8toTh98md5fRPwdAhKXKlPqCvUDgEI+HfQSuD7XX3N7fIpsc4iA2zcSlbMyZ2T0NKbbkKH2yT2ik5SqMbUwk5q1qywaeMTNiKTTxvmkHj9F3KWPVh/MX/6rwtUMH5GFbmMPbgG1QHlqle+8279HP/u8Q4/OovJ43igJDhb/xFOA1enKbI7jtHHSLqRNldCPBvxbJS+SUCPm7neMgCs5R9vQ5ldGV934NJ579136ReFg4RVSk6dCQe36H40DwTV98Wy73KxQNg1uQMY=
install:
  - pip install GitPython
  - export TRAVIS_COMMIT_MSG="$TRAVIS_REPO_SLUG - $(git log --format=%B --no-merges -n 1)"
script:
  - test "$TRAVIS_PULL_REQUEST" = "false" || travis_terminate 0
  - test "$TRAVIS_BRANCH" = "$TRAVIS_TAG" -o "$TRAVIS_BRANCH" = "master" || travis_terminate 0
  - git config --global user.email 'aussieaddons@aussieaddons.com'
  - git config --global user.name 'Aussie Add-ons Bot'
  - >
    git clone https://github.com/aussieaddons/repo-devel.git $TRAVIS_BUILD_DIR/.deploy-devel &&
    cd $TRAVIS_BUILD_DIR/.deploy-devel &&
    ./manage_repo.py $TRAVIS_BUILD_DIR || travis_terminate 1
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - >
    git add . &&
    git commit --allow-empty -m "$TRAVIS_COMMIT_MSG" &&
    git push || travis_terminate 1
  - if [ -z "$TRAVIS_TAG" ]; then travis_terminate 0; fi
  - >
    git clone https://github.com/aussieaddons/repo.git $TRAVIS_BUILD_DIR/.deploy-prod &&
    cd $TRAVIS_BUILD_DIR/.deploy-prod &&
    ./manage_repo.py $TRAVIS_BUILD_DIR || travis_terminate 1
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - >
    git add . &&
    git commit --allow-empty -m "Update $(basename `git -C $TRAVIS_BUILD_DIR rev-parse --show-toplevel`) to $TRAVIS_TAG" &&
    git push || travis_terminate 1
